name: Linting Pipeline

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: |
        npm install --save-dev htmlhint stylelint

    - name: Run HTMLHint
      run: |
        htmlhint '**/*.html'

    - name: Run Stylelint
      run: |
        stylelint '**/*.css'
